### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by Lordgeorge16** [Maki99999/music-by-biome#1] opened 2024-05-11 18:42 UTC
Just attempted to load this mod into the latest version of Minecraft (1.20.6), and got a huge series of errors.  I've attached the crash report .txt below.  I'm assuming this has something to do with the fact that the mod is only up to 1.20.1.  I don't have any other mods loaded, just the latest Forge API.  Are you planning on updating this soon, or was this crash caused by something else?  I'd really like to try it out and all of my friends' realms are up to 1.20.6!  Thanks in advance!

[crash-2024-05-11_14.37.51-fml.txt](https://github.com/Maki99999/music-by-biome/files/15283995/crash-2024-05-11_14.37.51-fml.txt)

**Comment by Maki99999** [comment] 2024-05-12 12:58
Yeah seems like it's incompatible with 1.20.5+. I'll aim to get to it when I have some free time. Thanks for letting me know.

**Comment by Maki99999** [comment] 2024-12-14 17:42
Duplicate of #9

**Closed by Maki99999** 2024-12-14 17:42 UTC
