### ISSUE TITLE
Error: java.lang.NullPointerException: Cannot invoke "io.github.maki99999.biomebeats.music.CustomMusic.getName()" because "this.currentMusic" is null

### ISSUE THREAD

**Issue by Mrglanet** [Maki99999/music-by-biome#3] opened 2024-06-27 19:16 UTC
I get this crash when I try to load a new world. It seems to point to this mod as the cause. Looks like it's thinking "this.currentMusic" within the code of this mod is null.

Crash log and latest log are below:

[crash-2024-06-27_13.57.56-client.txt](https://github.com/user-attachments/files/16020135/crash-2024-06-27_13.57.56-client.txt)

[latest.log](https://github.com/user-attachments/files/16020126/latest.log)

**Comment by sherpascott** [comment] 2024-08-29 04:35
I'm having the exact same issue

**Comment by Maki99999** [comment] 2024-08-30 12:14
I'm currently working on a 2.0 version of the mod that will fix the issue

**Comment by Maki99999** [comment] 2024-12-14 17:43
Duplicate of #9

**Closed by Maki99999** 2024-12-14 17:43 UTC
